[build]
    command = "npm run build"
    publish = ".output"

[functions]
  directory = ".netlify/functions"
  
[[redirects]]

    from = "/*"
    to = "/page/2025-04-27-geremy-contact"
    status = 200

[build.environment]
  NITRO_PRESET = "netlify"